### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by beenje**

### CODE REVIEW

**Comment by t-b** [comment]
@beenje Having an explicit license file is a good idea. Is the existing license already GPL? I can not find any reference in the code.

**Comment by beenje** [comment]
I took GPL because GPL or LGPL is what is used in other tango repositories: `cppTango`, `pytango`...
I'm not sure LGPL makes sense for `TangoTest` as it's a binary (for me LGPL is more for shared libraries). That's why I chose GPL.

After it's true that with GPL, there should be a reference in the source headers...

Or is it possible to use a MIT/BSD license instead?
A license is definitively needed.

**Comment by t-b** [comment]
@beenje I'm fine with GPL/MIT/BSD. Once we have agreed on the license we have to ask every existing contributor if they are okay with that (this is required from a legal POV).

**Comment by beenje** [comment]
Btw, discussion about adding a license started when packaging for Conda: https://github.com/beenje/staged-recipes/pull/1

**Comment by bourtemb** [comment]
> 
> 
> @beenje Having an explicit license file is a good idea. Is the existing license already GPL? I can not find any reference in the code.

GPLV3 or later is already specified in the headers of the source files.
For instance: https://github.com/tango-controls/TangoTest/blob/master/TangoTest.cpp#L17-L20

**Review by bourtemb — APPROVED** [review]

**Pull request merged**
