### PR TITLE
Added a DEV_NUM attribute

### PR DESCRIPTION
**Pull request by nleclercq**
Added a DEV_NUM attribute named "enum_scalar" (0:LABEL0, 1:LABEL1, 2:LABEL2).

### CODE REVIEW

**Comment by nleclercq** [comment]
@t-b @bourtemb Sorry guys I didn't notice that there's already a PR adding a DEV_NUM. I let you choose which one you want  to inject into the master.

**Comment by t-b** [comment]
@nleclercq We could merge yours first. Mine is adding also support for spectrum and image but this is not yet done.

But for merging we would need some changes:
- Drop wrong commits (rebase against master to get rid of the merge commit and the old commits from your previous PR)
- Regenerate the generated code with the latest master version of pogo. Since https://github.com/tango-controls/pogo/pull/102 pogo does now always output the std namespace prefix. And we want to keep that.

**Comment by nleclercq** [comment]
@t-b I'm supposed to do that? I'm not sure to fully understand what "drop wrong commits".

**Comment by t-b** [comment]
@nleclercq Yes.

Your branch `fix_wrt_long_image` containts the following commits:

```
$ git log --format=reference  master..
5d4c733 (Merge branch 'master' into fix_wrt_long_image, 2021-01-24)
374bd66 (added a DEV_NUM attribute, 2021-01-24)
9b1ae38 (added a DEV_ENUM attribute, 2021-01-23)
1df89e6 (fixed a crash in write_long_image; apply same fix to other data type and format, 2020-11-22)
58e2108 (fixed a crash in write_long_image, 2020-11-22)
```

Do a `git rebase -i origin/master` and change the todo list to

```
pick 9b1ae38 added a DEV_ENUM attribute
fixup 374bd66 added a DEV_NUM attribute
```

- Fix the conflicts
- Finish rebase
- Force push with `git push --force`

If you start with new branch from origin/master next time you can avoid much of these issues.

**Comment by nleclercq** [comment]
Ok. I see. My bad sorry. So I suggest resubmit a PR from a fresh branch and close this one.

**Comment by nleclercq** [comment]
I give up cause I don't have the right POGO version (I'm using 9.4.5).

**Comment by t-b** [comment]
@nleclercq You need pogo from the master branch.

**Pull request closed without merging**
